//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  research_streams: Research_Streams;
  research_streamsConnection: Research_StreamsConnection;
  lab_logs: Lab_Logs;
  lab_logsConnection: Lab_LogsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResearch_StreamsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResearch_StreamsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Research_StreamsFilter>;
};


export type QueryLab_LogsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLab_LogsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Lab_LogsFilter>;
};

export type DocumentFilter = {
  research_streams?: InputMaybe<Research_StreamsFilter>;
  lab_logs?: InputMaybe<Lab_LogsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Research_Streams | Lab_Logs | Folder;

export type Research_Streams = Node & Document & {
  __typename?: 'Research_streams';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  date: Scalars['String']['output'];
  author: Scalars['String']['output'];
  supervisor?: Maybe<Scalars['String']['output']>;
  status: Scalars['String']['output'];
  abstract: Scalars['String']['output'];
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  cover_image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Research_StreamsBodyEquationFilter = {
  equation?: InputMaybe<StringFilter>;
  display?: InputMaybe<BooleanFilter>;
};

export type Research_StreamsBodyCodeBlockFilter = {
  code?: InputMaybe<StringFilter>;
  language?: InputMaybe<StringFilter>;
};

export type Research_StreamsBodyFilter = {
  Equation?: InputMaybe<Research_StreamsBodyEquationFilter>;
  CodeBlock?: InputMaybe<Research_StreamsBodyCodeBlockFilter>;
};

export type Research_StreamsFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  supervisor?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  abstract?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  cover_image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<Research_StreamsBodyFilter>;
};

export type Research_StreamsConnectionEdges = {
  __typename?: 'Research_streamsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Research_Streams>;
};

export type Research_StreamsConnection = Connection & {
  __typename?: 'Research_streamsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Research_StreamsConnectionEdges>>>;
};

export type Lab_LogsParent_Stream = Research_Streams;

export type Lab_Logs = Node & Document & {
  __typename?: 'Lab_logs';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  log_type: Scalars['String']['output'];
  parent_stream: Lab_LogsParent_Stream;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  summary?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Lab_LogsParent_StreamFilter = {
  research_streams?: InputMaybe<Research_StreamsFilter>;
};

export type Lab_LogsBodyEquationFilter = {
  equation?: InputMaybe<StringFilter>;
  display?: InputMaybe<BooleanFilter>;
};

export type Lab_LogsBodyCodeBlockFilter = {
  code?: InputMaybe<StringFilter>;
  language?: InputMaybe<StringFilter>;
};

export type Lab_LogsBodyTableFilter = {
  caption?: InputMaybe<StringFilter>;
  data?: InputMaybe<StringFilter>;
};

export type Lab_LogsBodyFilter = {
  Equation?: InputMaybe<Lab_LogsBodyEquationFilter>;
  CodeBlock?: InputMaybe<Lab_LogsBodyCodeBlockFilter>;
  Table?: InputMaybe<Lab_LogsBodyTableFilter>;
};

export type Lab_LogsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  log_type?: InputMaybe<StringFilter>;
  parent_stream?: InputMaybe<Lab_LogsParent_StreamFilter>;
  tags?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  body?: InputMaybe<Lab_LogsBodyFilter>;
};

export type Lab_LogsConnectionEdges = {
  __typename?: 'Lab_logsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Lab_Logs>;
};

export type Lab_LogsConnection = Connection & {
  __typename?: 'Lab_logsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Lab_LogsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateResearch_streams: Research_Streams;
  createResearch_streams: Research_Streams;
  updateLab_logs: Lab_Logs;
  createLab_logs: Lab_Logs;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateResearch_StreamsArgs = {
  relativePath: Scalars['String']['input'];
  params: Research_StreamsMutation;
};


export type MutationCreateResearch_StreamsArgs = {
  relativePath: Scalars['String']['input'];
  params: Research_StreamsMutation;
};


export type MutationUpdateLab_LogsArgs = {
  relativePath: Scalars['String']['input'];
  params: Lab_LogsMutation;
};


export type MutationCreateLab_LogsArgs = {
  relativePath: Scalars['String']['input'];
  params: Lab_LogsMutation;
};

export type DocumentUpdateMutation = {
  research_streams?: InputMaybe<Research_StreamsMutation>;
  lab_logs?: InputMaybe<Lab_LogsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  research_streams?: InputMaybe<Research_StreamsMutation>;
  lab_logs?: InputMaybe<Lab_LogsMutation>;
};

export type Research_StreamsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  supervisor?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  abstract?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  cover_image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Lab_LogsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  log_type?: InputMaybe<Scalars['String']['input']>;
  parent_stream?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  summary?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Research_StreamsPartsFragment = { __typename: 'Research_streams', title: string, slug: string, date: string, author: string, supervisor?: string | null, status: string, abstract: string, tags?: Array<string | null> | null, keywords?: Array<string | null> | null, cover_image?: string | null, body?: any | null };

export type Lab_LogsPartsFragment = { __typename: 'Lab_logs', title: string, date: string, log_type: string, tags?: Array<string | null> | null, summary?: string | null, body?: any | null, parent_stream: { __typename: 'Research_streams', title: string, slug: string, date: string, author: string, supervisor?: string | null, status: string, abstract: string, tags?: Array<string | null> | null, keywords?: Array<string | null> | null, cover_image?: string | null, body?: any | null, id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Research_StreamsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Research_StreamsQuery = { __typename?: 'Query', research_streams: { __typename: 'Research_streams', id: string, title: string, slug: string, date: string, author: string, supervisor?: string | null, status: string, abstract: string, tags?: Array<string | null> | null, keywords?: Array<string | null> | null, cover_image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Research_StreamsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Research_StreamsFilter>;
}>;


export type Research_StreamsConnectionQuery = { __typename?: 'Query', research_streamsConnection: { __typename?: 'Research_streamsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Research_streamsConnectionEdges', cursor: string, node?: { __typename: 'Research_streams', id: string, title: string, slug: string, date: string, author: string, supervisor?: string | null, status: string, abstract: string, tags?: Array<string | null> | null, keywords?: Array<string | null> | null, cover_image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Lab_LogsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Lab_LogsQuery = { __typename?: 'Query', lab_logs: { __typename: 'Lab_logs', id: string, title: string, date: string, log_type: string, tags?: Array<string | null> | null, summary?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, parent_stream: { __typename: 'Research_streams', title: string, slug: string, date: string, author: string, supervisor?: string | null, status: string, abstract: string, tags?: Array<string | null> | null, keywords?: Array<string | null> | null, cover_image?: string | null, body?: any | null, id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } } };

export type Lab_LogsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Lab_LogsFilter>;
}>;


export type Lab_LogsConnectionQuery = { __typename?: 'Query', lab_logsConnection: { __typename?: 'Lab_logsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Lab_logsConnectionEdges', cursor: string, node?: { __typename: 'Lab_logs', id: string, title: string, date: string, log_type: string, tags?: Array<string | null> | null, summary?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, parent_stream: { __typename: 'Research_streams', title: string, slug: string, date: string, author: string, supervisor?: string | null, status: string, abstract: string, tags?: Array<string | null> | null, keywords?: Array<string | null> | null, cover_image?: string | null, body?: any | null, id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } } | null } | null> | null } };

export const Research_StreamsPartsFragmentDoc = gql`
    fragment Research_streamsParts on Research_streams {
  __typename
  title
  slug
  date
  author
  supervisor
  status
  abstract
  tags
  keywords
  cover_image
  body
}
    `;
export const Lab_LogsPartsFragmentDoc = gql`
    fragment Lab_logsParts on Lab_logs {
  __typename
  title
  date
  log_type
  parent_stream {
    ... on Research_streams {
      __typename
      title
      slug
      date
      author
      supervisor
      status
      abstract
      tags
      keywords
      cover_image
      body
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  tags
  summary
  body
}
    `;
export const Research_StreamsDocument = gql`
    query research_streams($relativePath: String!) {
  research_streams(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Research_streamsParts
  }
}
    ${Research_StreamsPartsFragmentDoc}`;
export const Research_StreamsConnectionDocument = gql`
    query research_streamsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Research_streamsFilter) {
  research_streamsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Research_streamsParts
      }
    }
  }
}
    ${Research_StreamsPartsFragmentDoc}`;
export const Lab_LogsDocument = gql`
    query lab_logs($relativePath: String!) {
  lab_logs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Lab_logsParts
  }
}
    ${Lab_LogsPartsFragmentDoc}`;
export const Lab_LogsConnectionDocument = gql`
    query lab_logsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Lab_logsFilter) {
  lab_logsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Lab_logsParts
      }
    }
  }
}
    ${Lab_LogsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      research_streams(variables: Research_StreamsQueryVariables, options?: C): Promise<{data: Research_StreamsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Research_StreamsQueryVariables, query: string}> {
        return requester<{data: Research_StreamsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Research_StreamsQueryVariables, query: string}, Research_StreamsQueryVariables>(Research_StreamsDocument, variables, options);
      },
    research_streamsConnection(variables?: Research_StreamsConnectionQueryVariables, options?: C): Promise<{data: Research_StreamsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Research_StreamsConnectionQueryVariables, query: string}> {
        return requester<{data: Research_StreamsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Research_StreamsConnectionQueryVariables, query: string}, Research_StreamsConnectionQueryVariables>(Research_StreamsConnectionDocument, variables, options);
      },
    lab_logs(variables: Lab_LogsQueryVariables, options?: C): Promise<{data: Lab_LogsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Lab_LogsQueryVariables, query: string}> {
        return requester<{data: Lab_LogsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Lab_LogsQueryVariables, query: string}, Lab_LogsQueryVariables>(Lab_LogsDocument, variables, options);
      },
    lab_logsConnection(variables?: Lab_LogsConnectionQueryVariables, options?: C): Promise<{data: Lab_LogsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Lab_LogsConnectionQueryVariables, query: string}> {
        return requester<{data: Lab_LogsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Lab_LogsConnectionQueryVariables, query: string}, Lab_LogsConnectionQueryVariables>(Lab_LogsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  